### PR TITLE
Callbacks explanations + tidying

### PR DESCRIPTION
**Pull request by catinsurance**
since callbacks can be strings or ints i used a pipe symbol "|" to denote two different possible types for the argument. also just general tidying. let me know about my wording.

### CODE REVIEW

**Comment by im-tem** [comment]
...can they actually be strings? enums are NOT strings and if the game DOES actually accept them as strings in those functions, i am worried

**Comment by Zamiell** [comment]
> ...can they actually be strings?

afaik the type used to be `int` but then it got changed to `int | string` to account for the new custom callbacks

in isaacscript it looks like this: https://github.com/IsaacScript/isaacscript/blob/main/packages/isaac-typescript-definitions/src/types/classes/Mod.d.ts#L27

**Comment by Sylmir** [comment]
From the patch notes of 1.7.9b on the Steam page, emphasis mine (here : https://store.steampowered.com/news/app/250900/view/3645131352093069363) :
- Added Isaac.RunCallback(callbackId, entityId, ...), runs all functions tied to the given callback and entityId (entityId can be nil for callbacks that do not depend on specific entity types)
- Isaac.AddCallback, Isaac.RemoveCallback and Isaac.RunCallback now accept **any value as a callback ID, even non-numeric values such as strings**, this may be used by mods to define custom callbacks for other mods to use

Let's ignore the fact that using any value is a great way for modders to completely mess up when using a reference value such as a userdata or a table. 

If we follow the patch notes, the type of the parameter should be `any`, however for the purpose of preventing headaches, limiting it to `string | number | ModCallback` is probably better.

**Comment by catinsurance** [comment]
> Let's ignore the fact that using any value is a great way for modders to completely mess up when using a reference value such as a userdata or a table.
> 
> If we follow the patch notes, the type of the parameter should be `any`, however for the purpose of preventing headaches, limiting it to `string | number | ModCallback` is probably better.

Yeah, that was my logic. `any` is _technically_ correct, but you shouldn't put `any`, just `string | number | ModCallback`. The explanation I wrote already is somewhat technically complicated so I wanted to keep it as simple as possible. I've updated all instances of "string|number" to "string|number|ModCallback" to better demonstrate that vanilla callback ids are fine, even though that's already implied.

**Comment by Zamiell** [comment]
`string | number | ModCallback` is incorrect, it should be `ModCallback | string` like it is in the isaacscript defs

**Pull request merged**
