### PR TITLE
Added descriptions to ItemConfig_Item.md

### PR DESCRIPTION
**Pull request by saturnaliam**
File had absolutely no information, so I added some.

Edit: All but ``Discharged`` have been added. Thanks to @Zamiell for giving input on all of these.
Exceptions are:
``IsCollectible()``
``IsNull()``
``IsTrinket()``
``Discharged``
``Special``
``Type``
because I frankly could not figure out what they were for.
(was tested locally)

### CODE REVIEW

**Comment by Zamiell** [comment]
the methods are identify methods, they do exactly what you would expect.
they aren't generally useful in the context of a mod because you aren't normally iterating through unknown items with the intent to filter

**Comment by Zamiell** [comment]
special is in reference to the special collectible reroll system pre-rep.
the system is still in the game but no items have the tag

**Comment by Zamiell** [comment]
type is the `ItemType`, for reference you can see https://github.com/IsaacScript/isaacscript/blob/main/packages/isaac-typescript-definitions/src/types/classes/ItemConfigItem.d.ts

**Comment by saturnaliam** [comment]
> the methods are identify methods, they do exactly what you would expect. they aren't generally useful in the context of a mod because you aren't normally iterating through unknown items with the intent to filter

Yeah, I assumed so but looking through like 15 different items I didn't see any change in them so I didn't write anything. Didn't wanna just guess for this.

**Pull request merged**
