### PR TITLE
mod config menu tutorial

### PR DESCRIPTION
**Pull request by laceous**

### CODE REVIEW

**Comment by Zamiell** [comment]
you should probably put this in the MCM docs and just link there from the IsaacDocs instead

**Comment by laceous** [comment]
Where's the MCM docs? I was having trouble finding anywhere better than the tutorials section here.

**Comment by Zamiell** [comment]
https://github.com/Zamiell/isaac-mod-config-menu/

**Comment by laceous** [comment]
Do you mean adding it to the readme there?

I was kind of hoping to have the quickstart guide not be tied specifically to the pure vs continued version, since there seems to be a split userbase on the workshop.

**Comment by Zamiell** [comment]
> Do you mean adding it to the readme there?

no, add it to a new file

**Comment by laceous** [comment]
I opened a PR against the MCM repo.

**Comment by Zamiell** [comment]
he's pretty slow about responding to PRs so if he doesn't respond then submit one to mine

**Pull request closed without merging**
