### PR TITLE
Added Infos and Bug boxes

### PR DESCRIPTION
**Pull request by Guantol-Lemat**
- Documented Isaac.Spawn crash.
- Added Notes to ItemPool:GetCollectible.
- Added additional Notes to MC_POST_CURSE_EVAL, MC_PRE/POST_GET_COLLECTIBLE and MC_PRE_CLEAN_AWARD.

### CODE REVIEW

**Comment by Zamiell** [comment]
can you have proof of the bug?

**Comment by Guantol-Lemat** [comment]
Made a video to showcase the crash: https://www.youtube.com/watch?v=DlEcuRUoMMo
Skip to around 3:35 for the actual test.

Another way to demonstrate the crash is:

Given that:
1. Game():Spawn(5, 100, Vector(320, 280), Vector(0, 0), nil, 0, 0) crashes the game.
2. Isaac.Spawn uses Random() to determine the seed.
3. Random() can return 0.

Isaac.Spawn can crash the game

**Comment by Zamiell** [comment]
how do you know that Isaac.Spawn uses Random() to determine the seed?

**Comment by Zamiell** [comment]
furthermore, any crash testing should be done on vanilla, since using repentogon can introduce a variety of crashes

**Comment by Guantol-Lemat** [comment]
> how do you know that Isaac.Spawn uses Random() to determine the seed instead of some custom, internal logic?

Yes

**Comment by Zamiell** [comment]
i entered the following console command:

```
l for i=1,100000000 do Isaac.DebugString("i: " .. tostring(i)); local entity = Isaac.Spawn(10,0,0,Vector(0,0),Vector(0,0),nil); Isaac.DebugString("seed: " .. tostring(entity.InitSeed)); if entity.InitSeed == 0 then break else entity:Remove() end end
```

i let it run for a few hours and it didn't spawn anything.
so again, i'll ask you for experimental evidence that can be reproduced on my side that what you say is actually true.

**Comment by Guantol-Lemat** [comment]
Here you go
[genrand_int32.lua.txt](https://github.com/user-attachments/files/15936243/genrand_int32.lua.txt)
After you run this file, do the following in the debug console
```lua
l NeededCalls = FindNextRandomZero() --Until it tells you that a zero has been found (might take multiple tries)
l for i = 1, NeededCalls - 1 do Random() end
l Isaac.Spawn(5, 100, 0, Vector(320, 280), Vector(0, 0), nil) --Make game go bye-bye
```

**Comment by Zamiell** [comment]
Perfect, thank you. I was able to reproduce the crash on my side.

**Pull request merged**
