### PR TITLE
Completed coded ingredient list

### PR DESCRIPTION
**Pull request by Xalum**
Thanks Blade!

### CODE REVIEW

**Comment by Xalum** [comment]
As a note this page doesn't actually appear to be appearing in the docs, and that's not something I know how to change

**Comment by Zamiell** [comment]
you just want it to appear in the xmls toc?

**Comment by Xalum** [comment]
I mean yeah, it wouldn't really make sense to be anywhere else

**Comment by Zamiell** [comment]
its as simple as typing ctrl+shift+f + rules.txt

**Comment by wofsauge** [comment]
> I mean yeah, it wouldn't really make sense to be anywhere else

You need to add an entry to the mkdocs.

> I mean yeah, it wouldn't really make sense to be anywhere else

You need to add an entry to the mkdocs.yml file as well

**Comment by Zamiell** [comment]
xalum can you add it to there?

**Pull request merged**
